package ats.algo.sport.tabletennis;

import ats.algo.core.common.TeamId;
import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.tabletennis.TabletennisMatchIncident.TabletennisMatchIncidentType;
import ats.algo.sport.tabletennis.TabletennisMatchIncidentResult.TabletennisMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class TabletennisMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class TabletennisMatchFacts {

        boolean setWinnerCurrentIsA;
        boolean setWinnerCurrentIsB;
        boolean setWinnerNextIsA;
        boolean matchWinnerisA;
        boolean setWinnerNPlus2IsA;
        boolean servePointIsA;
        boolean servePointNextIsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;

        boolean point3WinnerIsA;
        boolean point5WinnerIsA;
        boolean point7WinnerIsA;
        boolean point9WinnerIsA;
        boolean nextGamepoint3WinnerIsA;
        boolean nextGamepoint5WinnerIsA;
        boolean nextGamepoint7WinnerIsA;
        boolean nextGamepoint9WinnerIsA;

        boolean isTieBreak;
        int pointsA;
        int pointsB;
        double perWinningA;
        double perWinningB;
        int setsA;
        int setsB;
        int ID;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setWinnerCurrentIsA = false;
            setWinnerCurrentIsB = false;
            servePointIsA = false;
            servePointNextIsA = false;
            isTieBreak = false;

            point3WinnerIsA = false;
            point5WinnerIsA = false;
            point7WinnerIsA = false;
            point9WinnerIsA = false;
            nextGamepoint3WinnerIsA = false;
            nextGamepoint5WinnerIsA = false;
            nextGamepoint7WinnerIsA = false;
            nextGamepoint9WinnerIsA = false;
            pointsA = 0;
            pointsB = 0;
            setsA = 0;
            setsB = 0;
            ID = 0;

        }
    }

    private TabletennisMatchState simulationMatchState;
    private TabletennisMatchFacts matchFacts;

    public TabletennisMatch(TabletennisMatchFormat matchFormat, TabletennisMatchState matchState,
                    TabletennisMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new TabletennisMatchMarketsFactory(matchState);
        this.simulationMatchState = (TabletennisMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new TabletennisMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        TabletennisMatch cc = new TabletennisMatch((TabletennisMatchFormat) matchFormat,
                        (TabletennisMatchState) matchState, (TabletennisMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        boolean tieBreak;
        int startSetNo = simulationMatchState.getGamesA() + simulationMatchState.getGamesB() + 1;

        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstGame(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
                simulationMatchState.setServeNext(TeamId.A);
            } else {
                simulationMatchState.setServeInFirstGame(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
                simulationMatchState.setServeNext(TeamId.B);
            }
        tieBreak = (simulationMatchState.getPointsA() + simulationMatchState.getPointsB() >= 20);
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double p = ((TabletennisMatchParams) matchParams).getOnServePctA().nextRandom();
        double p1 = ((TabletennisMatchParams) matchParams).getOnServePctB().nextRandom();

        TabletennisMatchIncidentResult matchEventResult;
        matchFacts.reset();
        matchFacts.perWinningA = p;
        matchFacts.perWinningB = p1;
        matchFacts.servePointIsA = (simulationMatchState.getServe() == TeamId.A);
        matchFacts.servePointNextIsA = (simulationMatchState.getServeNext() == TeamId.A);
        matchFacts.isTieBreak = tieBreak;
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean pointWonByA;

            if (simulationMatchState.getServe() == TeamId.A)
                pointWonByA = r < p;
            else
                pointWonByA = r < 1 - p1;

            int currentSetNo = simulationMatchState.getGamesA() + simulationMatchState.getGamesB() + 1;

            if (pointWonByA) {

                TabletennisMatchIncident tabletennisMatchIncident = new TabletennisMatchIncident();
                tabletennisMatchIncident.set(TabletennisMatchIncidentType.POINTWON, TeamId.A);
                matchEventResult = (TabletennisMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(tabletennisMatchIncident, false);
            } else {
                TabletennisMatchIncident tabletennisMatchIncident = new TabletennisMatchIncident();
                tabletennisMatchIncident.set(TabletennisMatchIncidentType.POINTWON, TeamId.B);
                matchEventResult = (TabletennisMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(tabletennisMatchIncident, false);

            }
            TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getTabletennisMatchIncidentResultType()) {
                case POINTWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 3) && (simulationMatchState.getPointsB() < 3)) {
                                matchFacts.point3WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 3) && (simulationMatchState.getPointsB() == 3)) {
                                matchFacts.point3WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.point5WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.point5WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 7) && (simulationMatchState.getPointsB() < 7)) {
                                matchFacts.point7WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 7) && (simulationMatchState.getPointsB() == 7)) {
                                matchFacts.point7WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 9) && (simulationMatchState.getPointsB() < 9)) {
                                matchFacts.point9WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 9) && (simulationMatchState.getPointsB() == 9)) {
                                matchFacts.point9WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 3) && (simulationMatchState.getPointsB() < 3)) {
                                matchFacts.nextGamepoint3WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 3) && (simulationMatchState.getPointsB() == 3)) {
                                matchFacts.nextGamepoint3WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 7) && (simulationMatchState.getPointsB() < 7)) {
                                matchFacts.nextGamepoint7WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 7) && (simulationMatchState.getPointsB() == 7)) {
                                matchFacts.nextGamepoint7WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 9) && (simulationMatchState.getPointsB() < 9)) {
                                matchFacts.nextGamepoint9WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 9) && (simulationMatchState.getPointsB() == 9)) {
                                matchFacts.nextGamepoint9WinnerIsA = false;
                            }
                        }
                    }
                    break;
                case GAMEWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo)
                            matchFacts.setWinnerCurrentIsA = true;
                    } else if (currentSetNo == startSetNo)
                        matchFacts.setWinnerCurrentIsA = false;
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                    } else
                        matchFacts.matchWinnerisA = false;
                    break;
                default:
                    break;
            }

        } while (matchEventResult
                        .getTabletennisMatchIncidentResultType() != TabletennisMatchIncidentResultType.MATCHWON);
        ((TabletennisMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((TabletennisMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new TabletennisMatchMarketsFactory((TabletennisMatchState) matchState);

    }

}
