package ats.algo.sport.baseball;

import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.core.common.TeamId;
import ats.algo.sport.baseball.BaseballMatchFormat;
import ats.algo.sport.baseball.BaseballMatchIncident;
import ats.algo.sport.baseball.BaseballMatchIncident.BaseballMatchIncidentType;
import ats.algo.sport.baseball.BaseballMatchIncidentResult;
import ats.algo.sport.baseball.BaseballMatchIncidentResult.BaseballMatchPeriod;
import ats.algo.sport.baseball.BaseballMatchParams;
import ats.algo.sport.baseball.BaseballMatchState;
import ats.algo.montecarloframework.MonteCarloMatch;

public class BaseballMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class BaseballMatchFacts {
        TeamId firstRunTeam = TeamId.UNKNOWN;
        int runsA;
        int runsB;
        int oversA;
        int oversB;
        int ID;
        boolean currentOverA;
        boolean currentOverB;
        boolean currentWicketA;
        boolean currentWicketB;
        int currentRunsA;
        int currentRunsB;
        int nextRunsA;
        int nextRunsB;
        int wicketMethodA;
        int wicketMethodB;
        TeamId runs3Winner;
        TeamId runs5Winner;
        TeamId runs7Winner;

        void reset() {
            firstRunTeam = TeamId.UNKNOWN;
            runsA = 0;
            runsB = 0;
            oversA = 1;
            oversB = 1;
            ID = 0;
            currentRunsA = 0;
            currentRunsB = 0;
            currentOverA = false;
            currentWicketA = false;
            currentOverB = false;
            currentWicketB = false;
            wicketMethodA = -1;
            wicketMethodB = -1;
            runs3Winner = TeamId.UNKNOWN;
            runs5Winner = TeamId.UNKNOWN;
            runs7Winner = TeamId.UNKNOWN;
        }
    }

    private BaseballMatchState simulationMatchState;
    private BaseballMatchFacts matchFacts;
    // private int countA = 0;
    // private int countB = 0;
    /*
     * % chances of what will happen per ball for T20 No Runs - 55% 1 Run - 18% 2 Runs - 2.5% 3 Runs - 0.5% 4 Runs - 11%
     * 5 Runs - 0.2% 6 Runs - 5% Wicket - 1.5%Extras - 6.3% % Chance of dismissal Caught - 63% Bowled - 16% LBW - 12%
     * Run Out - 5% Stumped - 3% Other - 1%
     */

    // private final double[] ballPer = { 0.18, 0.025, 0.005, 0.11, 0.002, 0.05,
    // 0.063 };

    public BaseballMatch(BaseballMatchFormat matchFormat, BaseballMatchState matchState,
                    BaseballMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new BaseballMatchMarketsFactory(matchState);
        this.simulationMatchState = (BaseballMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */

        this.matchFacts = new BaseballMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        BaseballMatch cc = new BaseballMatch((BaseballMatchFormat) matchFormat, (BaseballMatchState) matchState,
                        (BaseballMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        // int nInningsInMatch = ((BaseballMatchFormat)
        // simulationMatchState.getMatchFormat()).getnInningsinMatch();
        // + ((BaseballMatchFormat)
        // simulationMatchState.getMatchFormat()).getnExtraInnings();
        if (simulationMatchState.getBat() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setBat(TeamId.A);
                simulationMatchState.setBatFirst(TeamId.A);
                simulationMatchState.setFirstHalf(true);
                simulationMatchState.setCurrentMatchState(
                                new BaseballMatchIncidentResult(BaseballMatchPeriod.FIRST_INNING_FIRST_HALF, TeamId.A));
            } else {
                simulationMatchState.setBat(TeamId.B);
                simulationMatchState.setFirstHalf(true);
                simulationMatchState.setBatFirst(TeamId.B);
                simulationMatchState.setCurrentMatchState(
                                new BaseballMatchIncidentResult(BaseballMatchPeriod.FIRST_INNING_FIRST_HALF, TeamId.B));
            }

        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        // double hit = 6.7; // ball number
        double tra = ((((BaseballMatchParams) matchParams).getTotalRuns().nextRandom()
                        + ((BaseballMatchParams) matchParams).getSupremacy().nextRandom())) / 2;
        if (tra / 30 < 0.21)
            tra = tra / 30;
        else if (tra / 30 < 0.25)
            tra = (tra / 30 + 0.21) / 2;
        else
            tra = (tra / 30 + 0.25) / 2;
        double trb = ((((BaseballMatchParams) matchParams).getTotalRuns().nextRandom()
                        - ((BaseballMatchParams) matchParams).getSupremacy().nextRandom())) / 2;
        if (trb / 30 < 0.21)
            trb = trb / 30;
        else if (trb / 30 < 0.25)
            trb = (trb / 30 + 0.21) / 2;
        else
            trb = (trb / 30 + 0.25) / 2;

        // tra = 0.0;
        // trb = 0.0;
        double hra = 0.0397;
        double hrb = 0.0397;
        double bata = 0.1132; // hit run rate
        double batb = 0.1132;
        double base1 = 0.2395;
        double base2 = 0.0697;
        double base3 = 0.0074;
        double soa = 0.4668;// Strike rate
        double sob = 0.4668;
        double balla = soa / 2;// Strike rate
        double ballb = sob / 2;
        double out = 0.0358;

        if (!simulationMatchState.isPitcherOneA()) {
            balla = balla * 1.35;
        }
        if (!simulationMatchState.isPitcherOneB()) {
            ballb = ballb * 1.35;
        }
        BaseballMatchIncidentResult matchEventResult;
        matchFacts.reset();

        // System.out.println(tra + "---" + trb + "--" + bata + "--" + batb);
        // System.out.println(bata * tra + "--" + batb * trb);
        double base1a = base1 + tra;
        double base2a = base2 + tra;
        double base3a = base3 + tra;
        hra = hra + tra;
        hrb = hrb + trb;
        double base1b = base1 + trb;
        double base2b = base2 + trb;
        double base3b = base3 + trb;
        // System.out.println(tra + "--" + trb + "--" + bata + "--" + batb +
        // "--" + soa + "--" + +balla + "--" + base1
        // + "--" + "--" + base2 + "--" + base3 + "--" + out + "--" + hra + "--"
        // + +(base1 + base2 + base3 + hra + out) + "-----" + (bata + soa +
        // balla));
        // bata = bata + tra;
        // batb = batb + trb;
        do {

            double r = RandomNoGenerator.nextDouble();
            boolean serveA = simulationMatchState.getBat() == TeamId.A;
            BaseballMatchIncident baseballMatchIncident = new BaseballMatchIncident();
            boolean onBase1 = false;
            boolean onBase2 = false;
            boolean onBase3 = false;
            if (serveA) {
                baseballMatchIncident.setTeamId(TeamId.A);
                if (simulationMatchState.getBaseInfo() == 0) {
                    if (r < bata * out) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                    } else if (r < bata * (out + base1a)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                    } else if (r < bata * (out + base1a + base2a)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                    } else if (r < bata * (out + base1a + base2a + base3a)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                    } else if (r < bata * (out + base1a + base2a + base3a + hra)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                    } else if (r < bata) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                    } else if (r < (bata + balla)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BALL);
                    } else {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.STRIKE);
                        matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                        .updateStateForIncident(baseballMatchIncident, false);
                        if (simulationMatchState.getStrike() == 0) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                        } else {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                        }
                    }

                } else {

                    onBase1 = false;
                    onBase2 = false;
                    onBase3 = false;
                    if (simulationMatchState.isBase1()) {
                        onBase1 = true;
                    }
                    if (simulationMatchState.isBase2()) {
                        onBase2 = true;
                    }
                    if (simulationMatchState.isBase3()) {
                        onBase3 = true;
                    }
                    if (r < (bata * out)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                    } else if (r < bata * (out + base1a + base2a + base3a + hra)) {
                        if (onBase1 && onBase2 && onBase3) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN2);
                            matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                            .updateStateForIncident(baseballMatchIncident, false);
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                            matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                            .updateStateForIncident(baseballMatchIncident, false);
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                        } else {
                            if (onBase1 && onBase2) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase1 && onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else if (onBase2 && onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else if (onBase2) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase1) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                            }
                        }

                    } else if (r < (bata)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                    } else if (r < (balla + bata)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BALL);
                    } else {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.STRIKE);
                        matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                        .updateStateForIncident(baseballMatchIncident, false);
                        if (simulationMatchState.getStrike() == 0) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                        } else {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                        }

                    }

                }

            } else {
                baseballMatchIncident.setTeamId(TeamId.B);
                if (simulationMatchState.getBaseInfo() == 0) {
                    if (r < batb * out) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                    } else if (r < batb * (out + base1b)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                    } else if (r < batb * (out + base1b + base2b)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                    } else if (r < batb * (out + base1b + base2b + base3b)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                    } else if (r < batb * (out + base1b + base2b + base3b + hrb)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                    } else if (r < batb) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                    } else if (r < (batb + ballb)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BALL);
                    } else {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.STRIKE);
                        matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                        .updateStateForIncident(baseballMatchIncident, false);
                        if (simulationMatchState.getStrike() == 0) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                        } else {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                        }
                    }

                } else {

                    onBase1 = false;
                    onBase2 = false;
                    onBase3 = false;
                    if (simulationMatchState.isBase1()) {
                        onBase1 = true;
                    }
                    if (simulationMatchState.isBase2()) {
                        onBase2 = true;
                    }
                    if (simulationMatchState.isBase3()) {
                        onBase3 = true;
                    }
                    if (r < (batb * out)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                    } else if (r < (batb * (out + base1b + base2b + base3b + hrb))) {
                        if (onBase1 && onBase2 && onBase3) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN2);
                            matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                            .updateStateForIncident(baseballMatchIncident, false);
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                            matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                            .updateStateForIncident(baseballMatchIncident, false);
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                        } else {
                            if (onBase1 && onBase2) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase1 && onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else if (onBase2 && onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase3) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.RUN1);
                                matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                                .updateStateForIncident(baseballMatchIncident, false);
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else if (onBase2) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE3);
                            } else if (onBase1) {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE2);
                            } else {
                                baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BASE1);
                            }
                        }

                    } else if (r < (batb)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                    } else if (r < (ballb + batb)) {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.BALL);
                    } else {
                        baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.STRIKE);
                        matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                                        .updateStateForIncident(baseballMatchIncident, false);
                        if (simulationMatchState.getStrike() == 0) {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.OUT);
                        } else {
                            baseballMatchIncident.setIncidentSubType(BaseballMatchIncidentType.NORUNS);
                        }
                    }

                }

            }
            // System.out.print(
            // baseballMatchIncident.getTeamId() + "--" +
            // baseballMatchIncident.getMatchIncidentType() + "--");
            if (simulationMatchState.getRunsA() + simulationMatchState.getRunsB() == 0)
                if (baseballMatchIncident.getIncidentSubType() == BaseballMatchIncidentType.RUN1
                                || baseballMatchIncident.getIncidentSubType() == BaseballMatchIncidentType.RUN2
                                || baseballMatchIncident.getIncidentSubType() == BaseballMatchIncidentType.RUN3
                                || baseballMatchIncident.getIncidentSubType() == BaseballMatchIncidentType.RUN4) {
                    matchFacts.firstRunTeam = baseballMatchIncident.getTeamId();
                }

            matchEventResult = (BaseballMatchIncidentResult) simulationMatchState
                            .updateStateForIncident(baseballMatchIncident, false);
            // System.out.println(simulationMatchState.isBase1() + "--" +
            // simulationMatchState.isBase2() + "--"
            // + simulationMatchState.isBase3() + "--" +
            // simulationMatchState.getBall() + "--"
            // + simulationMatchState.getStrike() + "--" +
            // simulationMatchState.getRunsA() + "--"
            // + simulationMatchState.getRunsB() + "--" +
            // simulationMatchState.getWicket() + "--"
            // + simulationMatchState.getInning() + "---------" + r + "---" +
            // baa + "---" + soa + "---" + hra+"--"+
            // + countA + "--" +
            // countB+"---"+matchEventResult.getBaseballMatchPeriod());

            switch (matchEventResult.getBaseballMatchPeriod()) {

                case MATCH_COMPLETED:
                case DRAW:
                    matchFacts.runsA = simulationMatchState.getRunsA();
                    matchFacts.runsB = simulationMatchState.getRunsB();
                    if (matchFacts.runs3Winner.equals(TeamId.UNKNOWN)) {

                        if (simulationMatchState.getRunsA() >= 3 && simulationMatchState.getRunsB() < 3)
                            matchFacts.runs3Winner = TeamId.A;
                        if (simulationMatchState.getRunsB() >= 3 && simulationMatchState.getRunsA() < 3)
                            matchFacts.runs3Winner = TeamId.B;
                    }
                    if (matchFacts.runs5Winner.equals(TeamId.UNKNOWN)) {
                        if (simulationMatchState.getRunsA() >= 5 && simulationMatchState.getRunsB() < 5)
                            matchFacts.runs5Winner = TeamId.A;
                        if (simulationMatchState.getRunsB() >= 5 && simulationMatchState.getRunsA() < 5)
                            matchFacts.runs5Winner = TeamId.B;
                    }
                    if (matchFacts.runs7Winner.equals(TeamId.UNKNOWN)) {
                        if (simulationMatchState.getRunsA() >= 7 && simulationMatchState.getRunsB() < 7)
                            matchFacts.runs7Winner = TeamId.A;
                        if (simulationMatchState.getRunsB() >= 7 && simulationMatchState.getRunsA() < 7)
                            matchFacts.runs7Winner = TeamId.B;
                    }
                    break;
                default:
                    break;
            }
        } while ((matchEventResult.getBaseballMatchPeriod() != BaseballMatchPeriod.MATCH_COMPLETED)
                        && (matchEventResult.getBaseballMatchPeriod() != BaseballMatchPeriod.DRAW));
        ((BaseballMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((BaseballMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new BaseballMatchMarketsFactory((BaseballMatchState) matchState);

    }

}
