package ats.algo.sport.tennis;

enum GameOrTieBreakEventResult {
    POINTWONA,
    POINTWONB,
    GAMEWONA,
    GAMEWONB,
    SUPERTIEBREAKSETWONA,
    SUPERTIEBREAKSETWONB,
    PENALTYMATCHWONA,
    PENALTYMATCHWONB
}
