package ats.algo.sport.beachvolleyball;

import ats.algo.core.common.TeamId;
import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.beachvolleyball.BeachVolleyballMatchIncident.BeachVolleyballMatchIncidentType;
import ats.algo.sport.beachvolleyball.BeachVolleyballMatchIncidentResult.BeachVolleyballMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class BeachVolleyballMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in AlgoMatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class BeachVolleyballMatchFacts {

        boolean setWinnerCurrentIsA;
        boolean setWinnerCurrentIsB;
        boolean setWinnerNextIsA;
        boolean matchWinnerisA;
        boolean setWinnerNPlus2IsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;
        boolean serveIsA;
        int pointsA;
        int pointsB;
        double pointWinningA;
        double pointWinningB;
        int setsA;
        int setsB;
        int ID;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setWinnerCurrentIsA = false;
            setWinnerCurrentIsB = false;
            serveIsA = false;
            pointWinningA = 0;
            pointWinningB = 0;
            pointsA = 0;
            pointsB = 0;
            setsA = 0;
            setsB = 0;
            ID = 0;

        }
    }

    private BeachVolleyballMatchState simulationMatchState;
    private BeachVolleyballMatchFacts matchFacts;

    public BeachVolleyballMatch(BeachVolleyballMatchFormat matchFormat, BeachVolleyballMatchState matchState,
                    BeachVolleyballMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new BeachVolleyballMatchMarketsFactory(matchState);
        this.simulationMatchState = (BeachVolleyballMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new BeachVolleyballMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        BeachVolleyballMatch cc = new BeachVolleyballMatch((BeachVolleyballMatchFormat) matchFormat,
                        (BeachVolleyballMatchState) matchState, (BeachVolleyballMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int startSetNo = simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1;

        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstSet(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
            } else {
                simulationMatchState.setServeInFirstSet(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
            }
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double p = ((BeachVolleyballMatchParams) matchParams).getOnServePctA().nextRandom();
        double p1 = ((BeachVolleyballMatchParams) matchParams).getOnServePctB().nextRandom();

        BeachVolleyballMatchIncidentResult matchEventResult;
        matchFacts.reset();
        matchFacts.pointWinningA = p;
        matchFacts.pointWinningB = p1;
        matchFacts.serveIsA = simulationMatchState.getServe() == TeamId.A;
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean pointWonByA;

            if (simulationMatchState.getServe() == TeamId.A)
                pointWonByA = r < p;
            else
                pointWonByA = r < 1 - p1;
            if (pointWonByA) {

                BeachVolleyballMatchIncident volleyballMatchIncident = new BeachVolleyballMatchIncident();
                volleyballMatchIncident.set(BeachVolleyballMatchIncidentType.POINTWON, TeamId.A);
                matchEventResult = (BeachVolleyballMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(volleyballMatchIncident, false);
            } else {
                BeachVolleyballMatchIncident volleyballMatchIncident = new BeachVolleyballMatchIncident();
                volleyballMatchIncident.set(BeachVolleyballMatchIncidentType.POINTWON, TeamId.B);
                matchEventResult = (BeachVolleyballMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(volleyballMatchIncident, false);

            }
            int currentSetNo = simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1;
            TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getVolleyballMatchIncidentResultType()) {
                case POINTWON:
                    break;
                case SETWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo)
                            matchFacts.setWinnerCurrentIsA = true;
                    } else if (currentSetNo == startSetNo)
                        matchFacts.setWinnerCurrentIsA = false;
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                    } else
                        matchFacts.matchWinnerisA = false;
                    break;
                default:
                    break;
            }

        } while (matchEventResult
                        .getVolleyballMatchIncidentResultType() != BeachVolleyballMatchIncidentResultType.MATCHWON);
        ((BeachVolleyballMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((BeachVolleyballMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new BeachVolleyballMatchMarketsFactory((BeachVolleyballMatchState) matchState);

    }

}
