package ats.algo.sport.bowls;

import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.bowls.BowlsMatchIncident.BowlsMatchIncidentType;
import ats.algo.sport.bowls.BowlsMatchIncidentResult.BowlsMatchIncidentResultType;
import ats.algo.core.common.TeamId;
import ats.algo.montecarloframework.MonteCarloMatch;

public class BowlsMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class BowlsMatchFacts {

        TeamId setCurrentWinner;
        TeamId setNextWinner;
        boolean raceToXPoints;
        boolean setWinnerCurrentIsB;
        boolean endWinnerCurrentIsA;
        boolean endWinnerNextIsA;
        boolean matchWinnerisA;
        boolean pointWinnerPlusTwoiSA;
        boolean pointWinnerNextisA;
        boolean pointWinnerNextPlusisA;
        boolean setWinnerNPlus2IsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;
        TeamId raceTo4Points;
        TeamId raceTo6Points;
        TeamId raceTo8Points;
        TeamId raceTo10Points;
        TeamId end3LeadIsA;
        TeamId end4LeadIsA;
        TeamId end5LeadIsA;
        TeamId end6LeadIsA;
        boolean end3Lead;
        boolean end4Lead;
        boolean end5Lead;
        boolean end6Lead;
        int pointsA;
        int pointsB;
        int totalPointsCurrentEnd;
        int totalPointsNextEnd;
        int setsA;
        int setsB;
        int ID;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setCurrentWinner = TeamId.UNKNOWN;
            setNextWinner = TeamId.UNKNOWN;
            raceTo4Points = TeamId.UNKNOWN;
            raceTo6Points = TeamId.UNKNOWN;
            raceTo8Points = TeamId.UNKNOWN;
            raceTo10Points = TeamId.UNKNOWN;
            end3LeadIsA = TeamId.UNKNOWN;
            end4LeadIsA = TeamId.UNKNOWN;
            end5LeadIsA = TeamId.UNKNOWN;
            end6LeadIsA = TeamId.UNKNOWN;

            setWinnerCurrentIsB = false;
            pointWinnerNextisA = false;
            pointWinnerNextisA = false;
            pointWinnerPlusTwoiSA = false;
            endWinnerCurrentIsA = false;
            endWinnerNextIsA = false;
            raceToXPoints = false;
            end3Lead = false;
            end4Lead = false;
            end5Lead = false;
            end6Lead = false;
            pointsA = 0;
            pointsB = 0;
            totalPointsCurrentEnd = 0;
            totalPointsNextEnd = 0;
            setsA = 0;
            setsB = 0;
            ID = 0;

        }
    }

    private BowlsMatchState simulationMatchState;
    private BowlsMatchFacts matchFacts;

    public BowlsMatch(BowlsMatchFormat matchFormat, BowlsMatchState matchState, BowlsMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new BowlsMatchMarketsFactory(matchState);
        this.simulationMatchState = (BowlsMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new BowlsMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        BowlsMatch cc = new BowlsMatch((BowlsMatchFormat) matchFormat, (BowlsMatchState) matchState,
                        (BowlsMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int startEndNo = simulationMatchState.getCurrentEnd();
        int startSetNo = (int) (simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1);
        int bowlsInEnd = simulationMatchState.getBowlsInEnd();
        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstSet(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
            } else {
                simulationMatchState.setServeInFirstSet(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
            }
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        // double pa = ((BowlsMatchParams) matchParams).getOnEndPctA()
        // .nextRandom();
        // double pb = 1 - ((BowlsMatchParams) matchParams).getOnEndPctB()
        // .nextRandom();
        // double p1 = ((BowlsMatchParams) matchParams).getOnCurrentEndPctA()
        // .nextRandom();
        double pa = ((BowlsMatchParams) matchParams).getParamMap().get("onEndPctA").getGaussian().nextRandom();
        double pb = 1 - ((BowlsMatchParams) matchParams).getParamMap().get("onEndPctB").getGaussian().nextRandom();
        double p1 = ((BowlsMatchParams) matchParams).getParamMap().get("onCurrentEndPctA").getGaussian().nextRandom();
        BowlsMatchIncidentResult matchEventResult;
        matchFacts.reset();
        do {
            int pointWon = 0;
            double r = RandomNoGenerator.nextDouble();
            double[] seA = new double[4];
            double[] seB = new double[4];

            int currentSetNo = (int) (simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1);
            int currentEndNo = simulationMatchState.getCurrentEnd();
            boolean serveA = (simulationMatchState.getServeInFirstSet() == TeamId.A);
            if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                // if (serveA) {
                seA[0] = p1 * 0.58;
                seA[1] = p1 * 0.28 + seA[0];
                seA[2] = p1 * 0.1 + seA[1];
                seA[3] = p1 * 0.04 + seA[2];
                seB[0] = p1 + (1 - p1) * 0.58;
                seB[1] = (1 - p1) * 0.28 + seB[0];
                seB[2] = (1 - p1) * 0.1 + +seB[1];
                seB[3] = (1 - p1) * 0.04 + seB[2];
                // } else {
                // seA[0] = (1 - p1) * 0.58;
                // seA[1] = (1 - p1) * 0.28 + seA[0];
                // seA[2] = (1 - p1) * 0.1 + seA[1];
                // seA[3] = (1 - p1) * 0.04 + seA[2];
                // seB[0] = (1 - p1) + p1 * 0.58;
                // seB[1] = p1 * 0.28 + seB[0];
                // seB[2] = p1 * 0.1 + +seB[1];
                // seB[3] = p1 * 0.04 + seB[2];
                // }

            } else {
                if (serveA) {
                    seA[0] = pa * 0.58;
                    seA[1] = pa * 0.28 + seA[0];
                    seA[2] = pa * 0.1 + seA[1];
                    seA[3] = pa * 0.04 + seA[2];
                    seB[0] = pa + (1 - pa) * 0.58;
                    seB[1] = (1 - pa) * 0.28 + seB[0];
                    seB[2] = (1 - pa) * 0.1 + +seB[1];
                    seB[3] = (1 - pa) * 0.04 + seB[2];
                } else {
                    seA[0] = pb * 0.58;
                    seA[1] = pb * 0.28 + seA[0];
                    seA[2] = pb * 0.1 + seA[1];
                    seA[3] = pb * 0.04 + seA[2];
                    seB[0] = pb + (1 - pb) * 0.58;
                    seB[1] = (1 - pb) * 0.28 + seB[0];
                    seB[2] = (1 - pb) * 0.1 + +seB[1];
                    seB[3] = (1 - pb) * 0.04 + seB[2];
                }
            }
            if (r < seA[0])
                pointWon = 1;
            if (r > seA[3] && r < seB[0])
                pointWon = -1;
            for (int i = 1; i < bowlsInEnd; i++) {
                if (r > seA[i - 1])
                    if (r < seA[i]) {
                        pointWon = i + 1;
                    }
                if (r > seB[i - 1])
                    if (r < seB[i]) {
                        pointWon = (i * -1) - 1;
                    }
            }
            TeamId teamId;
            BowlsMatchIncident bowlsMatchIncident = new BowlsMatchIncident();
            switch (pointWon) {
                case 1:
                    teamId = TeamId.A;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON1, teamId);
                    break;
                case 2:
                    teamId = TeamId.A;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON2, teamId);
                    break;
                case 3:
                    teamId = TeamId.A;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON3, teamId);
                    break;
                case 4:
                    teamId = TeamId.A;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON4, teamId);
                    break;
                case -1:
                    teamId = TeamId.B;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON1, teamId);
                    break;
                case -2:
                    teamId = TeamId.B;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON2, teamId);
                    break;
                case -3:
                    teamId = TeamId.B;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON3, teamId);
                    break;
                case -4:
                    teamId = TeamId.B;
                    bowlsMatchIncident.set(BowlsMatchIncidentType.ENDWON4, teamId);
                    break;
                default:
                    break;
            }

            matchEventResult = (BowlsMatchIncidentResult) simulationMatchState
                            .updateStateForIncident(bowlsMatchIncident, false);
            teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getBowlsMatchIncidentResultType()) {
                case ENDWON1:
                case ENDWON2:
                case ENDWON3:
                case ENDWON4:
                    if (TeamId.A == teamId) {
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = true;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo + 1)) {
                            matchFacts.endWinnerNextIsA = true;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsA() >= 4
                                        && simulationMatchState.getPointsB() < 4)
                            matchFacts.raceTo4Points = TeamId.A;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsA >= 4 && pointsB < 4)
                                matchFacts.raceTo4Points = TeamId.A;
                        }
                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsA() >= 6
                                        && simulationMatchState.getPointsB() < 6)
                            matchFacts.raceTo6Points = TeamId.A;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsA >= 6 && pointsB < 6)
                                matchFacts.raceTo6Points = TeamId.A;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsA() >= 8
                                        && simulationMatchState.getPointsB() < 8)
                            matchFacts.raceTo8Points = TeamId.A;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsA >= 8 && pointsB < 8)
                                matchFacts.raceTo8Points = TeamId.A;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsA() >= 10
                                        && simulationMatchState.getPointsB() < 10)
                            matchFacts.raceTo10Points = TeamId.A;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsA >= 10 && pointsB < 10)
                                matchFacts.raceTo10Points = TeamId.A;
                        }

                    } else {
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = false;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo + 1)) {
                            matchFacts.endWinnerNextIsA = false;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsB() >= 4
                                        && simulationMatchState.getPointsA() < 4)
                            matchFacts.raceTo4Points = TeamId.B;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsB >= 4 && pointsA < 4)
                                matchFacts.raceTo4Points = TeamId.B;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsB() >= 6
                                        && simulationMatchState.getPointsA() < 6)
                            matchFacts.raceTo6Points = TeamId.B;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsB >= 6 && pointsA < 6)
                                matchFacts.raceTo6Points = TeamId.B;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsB() >= 8
                                        && simulationMatchState.getPointsA() < 8)
                            matchFacts.raceTo8Points = TeamId.B;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsB >= 8 && pointsA < 8)
                                matchFacts.raceTo8Points = TeamId.B;
                        }

                        if ((currentSetNo == startSetNo) && simulationMatchState.getPointsB() >= 10
                                        && simulationMatchState.getPointsA() < 10)
                            matchFacts.raceTo10Points = TeamId.B;
                        if ((currentSetNo == startSetNo + 1) && simulationMatchState.getPointsA() == 0
                                        && simulationMatchState.getPointsB() == 0) {
                            int pointsA = simulationMatchState.getGameScoreInSetN(startSetNo).A;
                            int pointsB = simulationMatchState.getGameScoreInSetN(startSetNo).B;
                            if (pointsB >= 10 && pointsA < 10)
                                matchFacts.raceTo10Points = TeamId.B;
                        }
                    }

                    if ((currentSetNo == startSetNo) && (simulationMatchState.getCurrentEnd() == 4)
                                    && !matchFacts.end3Lead) {
                        if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                            matchFacts.end3LeadIsA = TeamId.A;
                        } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                            matchFacts.end3LeadIsA = TeamId.B;
                        } else {
                            matchFacts.end3LeadIsA = TeamId.UNKNOWN;
                        }
                        matchFacts.end3Lead = true;
                    }

                    if ((currentSetNo == startSetNo) && (simulationMatchState.getCurrentEnd() == 5)
                                    && !matchFacts.end4Lead) {
                        if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                            matchFacts.end4LeadIsA = TeamId.A;
                        } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                            matchFacts.end4LeadIsA = TeamId.B;
                        } else {
                            matchFacts.end4LeadIsA = TeamId.UNKNOWN;
                        }
                        matchFacts.end4Lead = true;
                    }

                    if ((currentSetNo == startSetNo) && (simulationMatchState.getCurrentEnd() == 6)
                                    && !matchFacts.end5Lead) {
                        if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                            matchFacts.end5LeadIsA = TeamId.A;
                        } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                            matchFacts.end5LeadIsA = TeamId.B;
                        } else {
                            matchFacts.end5LeadIsA = TeamId.UNKNOWN;
                        }
                        matchFacts.end5Lead = true;
                    }

                    if ((currentSetNo == startSetNo) && (simulationMatchState.getCurrentEnd() == 7)
                                    && !matchFacts.end6Lead) {
                        if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                            matchFacts.end6LeadIsA = TeamId.A;
                        } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                            matchFacts.end6LeadIsA = TeamId.B;
                        } else {
                            matchFacts.end6LeadIsA = TeamId.UNKNOWN;
                        }
                        matchFacts.end6Lead = true;
                    }
                    break;
                case SETWON:
                    if (TeamId.A == teamId) {
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = true;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo + 1)) {
                            matchFacts.endWinnerNextIsA = true;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }
                        if (currentSetNo == startSetNo)
                            matchFacts.setCurrentWinner = teamId;
                        if (currentSetNo == startSetNo + 1)
                            matchFacts.setNextWinner = teamId;
                    } else {
                        if (currentSetNo == startSetNo)
                            matchFacts.setCurrentWinner = teamId;
                        if (currentSetNo == startSetNo + 1)
                            matchFacts.setNextWinner = teamId;
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = false;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo + 1)) {
                            matchFacts.endWinnerNextIsA = false;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }
                    }
                    break;
                case SETDRAW:
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = true;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerNextIsA = true;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }
                        if (currentSetNo == startSetNo)
                            matchFacts.setCurrentWinner = teamId;
                        if (currentSetNo == startSetNo + 1)
                            matchFacts.setNextWinner = teamId;
                    } else {

                        matchFacts.matchWinnerisA = false;
                        if (currentSetNo == startSetNo)
                            matchFacts.setCurrentWinner = teamId;
                        if (currentSetNo == startSetNo + 1)
                            matchFacts.setNextWinner = teamId;
                        if ((currentSetNo == startSetNo + 1) && (currentEndNo == startEndNo)) {
                            matchFacts.endWinnerCurrentIsA = false;
                            matchFacts.totalPointsCurrentEnd = pointWon;
                        }
                        if ((currentSetNo == startSetNo + 1) && (currentEndNo == startEndNo + 1)) {
                            matchFacts.endWinnerNextIsA = false;
                            matchFacts.totalPointsNextEnd = pointWon;
                        }
                    }
                    break;
                default:
                    break;
            }

        } while (matchEventResult.getBowlsMatchIncidentResultType() != BowlsMatchIncidentResultType.MATCHWON);
        ((BowlsMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);

    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((BowlsMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new BowlsMatchMarketsFactory((BowlsMatchState) matchState);

    }

}
