package ats.algo.sport.cricket;

import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.core.common.TeamId;
import ats.algo.sport.cricket.CricketMatchIncident.CricketMatchIncidentType;
import ats.algo.sport.cricket.CricketMatchIncidentResult.CricketMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class CricketMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class CricketMatchFacts {

        int runsA;
        int runsB;
        int oversA;
        int oversB;
        int ID;
        boolean currentOverA;
        boolean currentOverB;
        boolean currentWicketA;
        boolean currentWicketB;
        int currentRunsA;
        int currentRunsB;
        int nextRunsA;
        int nextRunsB;
        int wicketMethodA;
        int wicketMethodB;

        void reset() {
            runsA = 0;
            runsB = 0;
            oversA = 1;
            oversB = 1;
            ID = 0;
            currentRunsA = 0;
            currentRunsB = 0;
            currentOverA = false;
            currentWicketA = false;
            currentOverB = false;
            currentWicketB = false;
            wicketMethodA = -1;
            wicketMethodB = -1;
        }
    }

    private CricketMatchState simulationMatchState;
    private CricketMatchFacts matchFacts;
    /*
     * % chances of what will happen per ball for T20 No Runs - 55% 1 Run - 18% 2 Runs - 2.5% 3 Runs - 0.5% 4 Runs - 11%
     * 5 Runs - 0.2% 6 Runs - 5% Wicket - 1.5%Extras - 6.3% % Chance of dismissal Caught - 63% Bowled - 16% LBW - 12%
     * Run Out - 5% Stumped - 3% Other - 1%
     */

    // private final double[] ballPer = { 0.18, 0.025, 0.005, 0.11, 0.002, 0.05,
    // 0.063 };
    private final double[] ballPer1to6 = {0.23, 0.07, 0.005, 0.13, 0.002, 0.04, 0.029};
    private final double[] ballPer7to16 = {0.36, 0.12, 0.005, 0.07, 0.002, 0.03, 0.023};
    private final double[] ballPer17to20 = {0.27, 0.13, 0.005, 0.14, 0.002, 0.06, 0.033};
    private final double[] wicketPer = {0.63, 0.16, 0.12, 0.05, 0.03, 0.01};

    private final double[] per = new double[ballPer1to6.length + wicketPer.length];
    private double sum = 0;
    private double sum1to6 = 0;
    private double sum7to16 = 0;
    private double sum17to20 = 0;
    private double sum1to10 = 48.07;
    private double sum11to40 = 146.11;
    private double sum41to50 = 68.35;
    // private double sumAll = 0;
    private int totalBalls;
    private boolean ratio = true;

    public CricketMatch(CricketMatchFormat matchFormat, CricketMatchState matchState, CricketMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new CricketMatchMarketsFactory(matchState);
        this.simulationMatchState = (CricketMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */

        this.matchFacts = new CricketMatchFacts();
        totalBalls = matchFormat.getnBallsinOver() * matchFormat.getnOversinMatch();
        for (int i = 0; i < ballPer1to6.length; i++) {
            if (i == ballPer1to6.length - 1) {
                sum1to6 += ballPer1to6[i];
            } else
                sum1to6 += (i + 1) * ballPer1to6[i];
        }
        sum = sum1to6 * totalBalls;
        if (ratio) {
            sum = sum1to6 * 36;
            for (int i = 0; i < ballPer7to16.length; i++) {
                if (i == ballPer7to16.length - 1) {
                    sum7to16 += ballPer7to16[i];
                } else
                    sum7to16 += (i + 1) * ballPer7to16[i];
            }
            sum += sum7to16 * 60;
            for (int i = 0; i < ballPer17to20.length; i++) {
                if (i == ballPer17to20.length - 1) {
                    sum17to20 += ballPer17to20[i];
                } else
                    sum17to20 += (i + 1) * ballPer17to20[i];
            }
            if (matchFormat.getnOversinMatch() == 20)
                sum += sum17to20 * 24;
            else {
                sum = (sum1to10 + sum11to40 + sum41to50) * 1.33;
            }
        }
    }

    @Override
    public MonteCarloMatch clone() {
        CricketMatch cc = new CricketMatch((CricketMatchFormat) matchFormat, (CricketMatchState) matchState,
                        (CricketMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        totalBalls = ((CricketMatchFormat) matchFormat).getnBallsinOver()
                        * ((CricketMatchFormat) matchFormat).getnOversinMatch();
        boolean freeHit = simulationMatchState.isFreeHit();
        int currentWicketA = simulationMatchState.getWicketsA();
        int currentWicketB = simulationMatchState.getWicketsB();
        if (simulationMatchState.getBat() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setBat(TeamId.A);
            } else {
                simulationMatchState.setBat(TeamId.B);
            }

        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double pa = ((CricketMatchParams) matchParams).getTeamAScoreRate().nextRandom();
        double pb = ((CricketMatchParams) matchParams).getTeamBScoreRate().nextRandom();
        if (freeHit) {
            pa = pa + 1;
            pb = pb + 1;
        }
        double wicket1to6 = 0.024;
        double wicket7to16 = 0.025;
        double wicket17to20 = 0.04;
        double wicket1to10 = 1.5 / 60;
        double wicket11to40 = 3.8 / 180;
        double wicket41to50 = 2.91 / 60;

        double ta;
        double tb;
        double[] perA1to6 = new double[per.length];
        double[] perB1to6 = new double[per.length];
        double[] perA7to16 = new double[per.length];
        double[] perB7to16 = new double[per.length];
        double[] perA17to20 = new double[per.length];
        double[] perB17to20 = new double[per.length];

        ta = pa / sum;
        tb = pb / sum;
        if (((CricketMatchFormat) matchFormat).getnOversinMatch() == 20) {
            perA1to6[0] = ballPer1to6[0] * ta;
            for (int i = 1; i < perA1to6.length; i++)
                if (i > (ballPer1to6.length - 1))
                    perA1to6[i] = wicket1to6 * wicketPer[i - ballPer1to6.length] + perA1to6[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA1to6[i] += ballPer1to6[m] * ta;
            perB1to6[0] = ballPer1to6[0] * tb;
            for (int i = 1; i < perB1to6.length; i++)
                if (i > (ballPer1to6.length - 1))
                    perB1to6[i] = wicket1to6 * wicketPer[i - ballPer1to6.length] + perB1to6[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB1to6[i] += ballPer1to6[m] * tb;
            perA17to20[0] = ballPer17to20[0] * ta;
            for (int i = 1; i < perA17to20.length; i++)
                if (i > (ballPer17to20.length - 1))
                    perA17to20[i] = wicket17to20 * wicketPer[i - ballPer17to20.length] + perA17to20[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA17to20[i] += ballPer17to20[m] * ta;
            perB17to20[0] = ballPer17to20[0] * tb;
            for (int i = 1; i < perB17to20.length; i++)
                if (i > (ballPer17to20.length - 1))
                    perB17to20[i] = wicket17to20 * wicketPer[i - ballPer17to20.length] + perB17to20[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB17to20[i] += ballPer17to20[m] * tb;
            perA7to16[0] = ballPer7to16[0] * ta;
            for (int i = 1; i < perA7to16.length; i++)
                if (i > (ballPer7to16.length - 1))
                    perA7to16[i] = wicket7to16 * wicketPer[i - ballPer7to16.length] + perA7to16[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA7to16[i] += ballPer7to16[m] * ta;
            perB7to16[0] = ballPer7to16[0] * tb;
            for (int i = 1; i < perB7to16.length; i++)
                if (i > (ballPer7to16.length - 1))
                    perB7to16[i] = wicket7to16 * wicketPer[i - ballPer7to16.length] + perB7to16[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB7to16[i] += ballPer7to16[m] * tb;
        } else {
            perA1to6[0] = ballPer1to6[0] * ta;
            for (int i = 1; i < perA1to6.length; i++)
                if (i > (ballPer1to6.length - 1))
                    perA1to6[i] = wicket1to10 * wicketPer[i - ballPer1to6.length] + perA1to6[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA1to6[i] += ballPer1to6[m] * ta;
            perB1to6[0] = ballPer1to6[0] * tb;
            for (int i = 1; i < perB1to6.length; i++)
                if (i > (ballPer1to6.length - 1))
                    perB1to6[i] = wicket1to10 * wicketPer[i - ballPer1to6.length] + perB1to6[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB1to6[i] += ballPer1to6[m] * tb;
            perA17to20[0] = ballPer17to20[0] * ta;
            for (int i = 1; i < perA17to20.length; i++)
                if (i > (ballPer17to20.length - 1))
                    perA17to20[i] = wicket41to50 * wicketPer[i - ballPer17to20.length] + perA17to20[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA17to20[i] += ballPer17to20[m] * ta;
            perB17to20[0] = ballPer17to20[0] * tb;
            for (int i = 1; i < perB17to20.length; i++)
                if (i > (ballPer17to20.length - 1))
                    perB17to20[i] = wicket41to50 * wicketPer[i - ballPer17to20.length] + perB17to20[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB17to20[i] += ballPer17to20[m] * tb;
            perA7to16[0] = ballPer7to16[0] * ta;
            for (int i = 1; i < perA7to16.length; i++)
                if (i > (ballPer7to16.length - 1))
                    perA7to16[i] = wicket11to40 * wicketPer[i - ballPer7to16.length] + perA7to16[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA7to16[i] += ballPer7to16[m] * ta;
            perB7to16[0] = ballPer7to16[0] * tb;
            for (int i = 1; i < perB7to16.length; i++)
                if (i > (ballPer7to16.length - 1))
                    perB7to16[i] = wicket11to40 * wicketPer[i - ballPer7to16.length] + perB7to16[i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB7to16[i] += ballPer7to16[m] * tb;
        }

        CricketMatchIncidentResult matchEventResult;
        matchFacts.reset();

        do {
            double r = RandomNoGenerator.nextDouble();
            int simulatedOverNoA = simulationMatchState.getOversA();
            int simulatedOverNoB = simulationMatchState.getOversB();

            boolean serveA = simulationMatchState.getBat() == TeamId.A;

            CricketMatchIncident cricketMatchIncident = new CricketMatchIncident();
            if (serveA) {
                cricketMatchIncident.setTeamId(TeamId.A);
            } else
                cricketMatchIncident.setTeamId(TeamId.B);
            if (((CricketMatchFormat) matchFormat).getnOversinMatch() == 20) {
                if (serveA) {
                    if (simulatedOverNoA < 7) {
                        if (r < (perA1to6[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA1to6[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA1to6[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA1to6[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA1to6[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA1to6[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA1to6[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA1to6[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA1to6[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA1to6[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA1to6[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA1to6[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA1to6[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else if (simulatedOverNoA > 16) {
                        if (r < (perA17to20[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA17to20[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA17to20[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA17to20[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA17to20[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA17to20[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA17to20[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA17to20[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA17to20[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA17to20[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA17to20[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA17to20[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA17to20[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else {
                        if (r < (perA7to16[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA7to16[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA7to16[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA7to16[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA7to16[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA7to16[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA7to16[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA7to16[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA7to16[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA7to16[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA7to16[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA7to16[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA7to16[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    }

                } else {

                    if (simulatedOverNoB < 7) {
                        if (r < (perB1to6[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB1to6[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB1to6[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB1to6[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB1to6[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB1to6[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB1to6[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB1to6[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB1to6[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB1to6[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB1to6[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB1to6[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB1to6[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }

                    } else if (simulatedOverNoB > 16) {
                        if (r < (perB17to20[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB17to20[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB17to20[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB17to20[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB17to20[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB17to20[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB17to20[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB17to20[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB17to20[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB17to20[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB17to20[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB17to20[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB17to20[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else {
                        if (r < (perB7to16[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB7to16[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB7to16[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB7to16[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB7to16[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB7to16[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB7to16[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB7to16[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB7to16[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB7to16[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB7to16[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB7to16[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB7to16[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    }
                }
            } else {
                if (serveA) {
                    if (simulatedOverNoA < 11) {
                        if (r < (perA1to6[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA1to6[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA1to6[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA1to6[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA1to6[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA1to6[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA1to6[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA1to6[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA1to6[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA1to6[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA1to6[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA1to6[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA1to6[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else if (simulatedOverNoA > 40) {
                        if (r < (perA17to20[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA17to20[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA17to20[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA17to20[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA17to20[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA17to20[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA17to20[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA17to20[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA17to20[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA17to20[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA17to20[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA17to20[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA17to20[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else {
                        if (r < (perA7to16[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perA7to16[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perA7to16[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perA7to16[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perA7to16[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perA7to16[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perA7to16[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perA7to16[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perA7to16[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perA7to16[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perA7to16[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perA7to16[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perA7to16[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    }

                } else {

                    if (simulatedOverNoB < 11) {
                        if (r < (perB1to6[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB1to6[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB1to6[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB1to6[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB1to6[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB1to6[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB1to6[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB1to6[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB1to6[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB1to6[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB1to6[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB1to6[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB1to6[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }

                    } else if (simulatedOverNoB > 40) {
                        if (r < (perB17to20[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB17to20[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB17to20[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB17to20[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB17to20[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB17to20[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB17to20[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB17to20[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB17to20[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB17to20[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB17to20[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB17to20[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB17to20[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    } else {
                        if (r < (perB7to16[0])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                        } else if (r < (perB7to16[1])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                        } else if (r < (perB7to16[2])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                        } else if (r < (perB7to16[3])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                        } else if (r < (perB7to16[4])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                        } else if (r < (perB7to16[5])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                        } else if (r < (perB7to16[6])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                        } else if (r < (perB7to16[7])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                        } else if (r < (perB7to16[8])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                        } else if (r < (perB7to16[9])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                        } else if (r < (perB7to16[10])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                        } else if (r < (perB7to16[11])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                        } else if (r < (perB7to16[12])) {
                            cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                        } else {
                            cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                        }
                    }
                }
            }

            matchEventResult = (CricketMatchIncidentResult) simulationMatchState
                            .updateStateForIncident(cricketMatchIncident, false);
            int x = -1;
            // TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getcricketMatchIncidentResultType()) {

                case WICKET_BOWLED:
                    x++;
                case WICKET_CAUGHT:
                    x++;
                case WICKET_LBW:
                    x++;
                case WICKET_RUN_OUT:
                    x++;
                case WICKET_STUMPED:
                    x++;
                case WICKET_OTHER:
                    x++;
                    if (x != -1 && simulationMatchState.getWicketsA() == (currentWicketA + 1)
                                    && !matchFacts.currentWicketA && serveA) {
                        matchFacts.currentWicketA = true;
                        matchFacts.wicketMethodA = 5 - x;
                    }
                    if (x != -1 && simulationMatchState.getWicketsB() == (currentWicketB + 1)
                                    && !matchFacts.currentWicketB && !serveA) {
                        matchFacts.currentWicketB = true;
                        matchFacts.wicketMethodB = 5 - x;
                    }
                case NORUNS:
                case RUN1:
                case RUN2:
                case RUN3:
                case RUN4:
                case RUN5:
                case RUN6:
                    break;
                case MATCHWON:
                case DRAW:
                    matchFacts.runsA = simulationMatchState.getRunsA();
                    matchFacts.runsB = simulationMatchState.getRunsB();
                    if (serveA) {
                        if (matchEventResult.isLastPointWicket()) {
                            matchFacts.currentWicketA = true;
                            matchFacts.wicketMethodA = matchEventResult.getWicketType();

                        }
                    } else {
                        if (matchEventResult.isLastPointWicket()) {
                            matchFacts.currentWicketB = true;
                            matchFacts.wicketMethodB = matchEventResult.getWicketType();

                        }
                    }

                    break;
                default:
                    break;
            }
        } while ((matchEventResult.getcricketMatchIncidentResultType() != CricketMatchIncidentResultType.MATCHWON)
                        && (matchEventResult
                                        .getcricketMatchIncidentResultType() != CricketMatchIncidentResultType.DRAW));
        ((CricketMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((CricketMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new CricketMatchMarketsFactory((CricketMatchState) matchState);

    }

}
