package ats.algo.sport.badminton;

import ats.algo.core.common.TeamId;
import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.badminton.BadmintonMatchIncident.BadmintonMatchIncidentType;
import ats.algo.sport.badminton.BadmintonMatchIncidentResult.BadmintonMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class BadmintonMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Geoff
     * 
     */
    class BadmintonMatchFacts {

        boolean setWinnerCurrentIsA;
        boolean setWinnerCurrentIsB;
        boolean setWinnerNextIsA;
        boolean matchWinnerisA;
        boolean setWinnerNPlus2IsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;
        boolean serveIsA;
        boolean point5WinnerIsA;
        TeamId point10LeadIsA;
        boolean point10WinnerIsA;
        TeamId point20LeadIsA;
        boolean point15WinnerIsA;
        TeamId point30LeadIsA;

        TeamId nextGamepoint5WinnerIsA;
        TeamId nextGamepoint10LeadIsA;
        TeamId nextGamepoint10WinnerIsA;
        TeamId nextGamepoint20LeadIsA;
        TeamId nextGamepoint15WinnerIsA;
        TeamId nextGamepoint30LeadIsA;
        int pointsA;
        int pointsB;
        double pointWinningA;
        double pointWinningB;
        int setsA;
        int setsB;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setWinnerCurrentIsA = false;
            setWinnerCurrentIsB = false;
            point5WinnerIsA = false;
            point10LeadIsA = TeamId.UNKNOWN;
            point10WinnerIsA = false;
            point20LeadIsA = TeamId.UNKNOWN;
            point15WinnerIsA = false;
            point30LeadIsA = TeamId.UNKNOWN;

            nextGamepoint5WinnerIsA = TeamId.UNKNOWN;
            nextGamepoint10LeadIsA = TeamId.UNKNOWN;
            nextGamepoint10WinnerIsA = TeamId.UNKNOWN;
            nextGamepoint20LeadIsA = TeamId.UNKNOWN;
            nextGamepoint15WinnerIsA = TeamId.UNKNOWN;
            nextGamepoint30LeadIsA = TeamId.UNKNOWN;
            serveIsA = false;
            pointWinningA = 0;
            pointWinningB = 0;
            pointsA = 0;
            pointsB = 0;
            setsA = 0;
            setsB = 0;
        }
    }

    private BadmintonMatchState simulationMatchState;
    private BadmintonMatchFacts matchFacts;

    public BadmintonMatch(BadmintonMatchFormat matchFormat, BadmintonMatchState matchState,
                    BadmintonMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new BadmintonMatchMarketsFactory(matchState);
        this.simulationMatchState = (BadmintonMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new BadmintonMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        return new BadmintonMatch((BadmintonMatchFormat) matchFormat, (BadmintonMatchState) matchState,
                        (BadmintonMatchParams) matchParams);
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int startSetNo = simulationMatchState.getGamesA() + simulationMatchState.getGamesB() + 1;

        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstGame(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
            } else {

                simulationMatchState.setServeInFirstGame(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
            }
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double p = ((BadmintonMatchParams) matchParams).getOnServePctA().nextRandom();

        BadmintonMatchIncidentResult matchEventResult;
        matchFacts.reset();
        matchFacts.pointWinningA = p;
        matchFacts.serveIsA = simulationMatchState.getServe() == TeamId.A;
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean pointWonByA;

            pointWonByA = r < p;

            if (pointWonByA) {

                BadmintonMatchIncident badmintonMatchIncident = new BadmintonMatchIncident();
                badmintonMatchIncident.set(BadmintonMatchIncidentType.POINTWON, TeamId.A);
                matchEventResult = (BadmintonMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(badmintonMatchIncident, false);
            } else {
                BadmintonMatchIncident badmintonMatchIncident = new BadmintonMatchIncident();
                badmintonMatchIncident.set(BadmintonMatchIncidentType.POINTWON, TeamId.B);
                matchEventResult = (BadmintonMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(badmintonMatchIncident, false);

            }
            int currentSetNo = simulationMatchState.getGamesA() + simulationMatchState.getGamesB() + 1;
            int pointNo = simulationMatchState.getPointsA() + simulationMatchState.getPointsB();
            TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getBadmintonMatchIncidentResultType()) {
                case POINTWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.point5WinnerIsA = true;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.point5WinnerIsA = false;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 10) && (simulationMatchState.getPointsB() < 10)) {
                                matchFacts.point10WinnerIsA = true;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 10) && (simulationMatchState.getPointsB() == 10)) {
                                matchFacts.point10WinnerIsA = false;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 15) && (simulationMatchState.getPointsB() < 15)) {
                                matchFacts.point15WinnerIsA = true;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point30LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 15) && (simulationMatchState.getPointsB() == 15)) {
                                matchFacts.point15WinnerIsA = false;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point30LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = TeamId.A;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = TeamId.B;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 10) && (simulationMatchState.getPointsB() < 10)) {
                                matchFacts.nextGamepoint10WinnerIsA = TeamId.A;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 10) && (simulationMatchState.getPointsB() == 10)) {
                                matchFacts.nextGamepoint10WinnerIsA = TeamId.B;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 15) && (simulationMatchState.getPointsB() < 15)) {
                                matchFacts.nextGamepoint15WinnerIsA = TeamId.A;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 15) && (simulationMatchState.getPointsB() == 15)) {
                                matchFacts.nextGamepoint15WinnerIsA = TeamId.B;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.nextGamepoint30LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }
                    break;
                case GAMEWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo)
                            matchFacts.setWinnerCurrentIsA = true;
                    } else if (currentSetNo == startSetNo)
                        matchFacts.setWinnerCurrentIsA = false;
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                    } else
                        matchFacts.matchWinnerisA = false;
                    break;
                default:
                    break;
            }

        } while (matchEventResult.getBadmintonMatchIncidentResultType() != BadmintonMatchIncidentResultType.MATCHWON);
        ((BadmintonMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((BadmintonMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new BadmintonMatchMarketsFactory((BadmintonMatchState) matchState);

    }

}
