package ats.algo.sport.squash;

import ats.algo.core.common.TeamId;
import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.squash.SquashMatchIncident.SquashMatchIncidentType;
import ats.algo.sport.squash.SquashMatchIncidentResult.SquashMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class SquashMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class SquashMatchFacts {

        boolean setWinnerCurrentIsA;
        boolean setWinnerCurrentIsB;
        boolean setWinnerNextIsA;
        boolean matchWinnerisA;
        boolean setWinnerNPlus2IsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;
        boolean serveIsA;
        boolean point3WinnerIsA;
        boolean point5WinnerIsA;
        boolean point7WinnerIsA;
        boolean point9WinnerIsA;
        boolean nextGamepoint3WinnerIsA;
        boolean nextGamepoint5WinnerIsA;
        boolean nextGamepoint7WinnerIsA;
        boolean nextGamepoint9WinnerIsA;
        int pointsA;
        int pointsB;
        double pointWinningA;
        double pointWinningB;
        int setsA;
        int setsB;
        int ID;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setWinnerCurrentIsA = false;
            setWinnerCurrentIsB = false;
            serveIsA = false;

            point3WinnerIsA = false;
            point5WinnerIsA = false;
            point7WinnerIsA = false;
            point9WinnerIsA = false;
            nextGamepoint3WinnerIsA = false;
            nextGamepoint5WinnerIsA = false;
            nextGamepoint7WinnerIsA = false;
            nextGamepoint9WinnerIsA = false;
            pointsA = 0;
            pointsB = 0;
            setsA = 0;
            setsB = 0;
            ID = 0;

        }
    }

    private SquashMatchState simulationMatchState;
    private SquashMatchFacts matchFacts;

    public SquashMatch(SquashMatchFormat matchFormat, SquashMatchState matchState, SquashMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new SquashMatchMarketsFactory(matchState);
        this.simulationMatchState = (SquashMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new SquashMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        SquashMatch cc = new SquashMatch((SquashMatchFormat) matchFormat, (SquashMatchState) matchState,
                        (SquashMatchParams) matchParams);
        return cc;
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int startSetNo = simulationMatchState.getGamesA() + simulationMatchState.getGamesB() + 1;

        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstGame(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
            } else {
                simulationMatchState.setServeInFirstGame(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
            }
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double p = ((SquashMatchParams) matchParams).getOnServePctA().nextRandom();
        double p1 = ((SquashMatchParams) matchParams).getOnServePctB().nextRandom();

        SquashMatchIncidentResult matchEventResult;
        matchFacts.reset();
        matchFacts.reset();
        matchFacts.pointWinningA = p;
        matchFacts.pointWinningB = p1;
        matchFacts.serveIsA = simulationMatchState.getServe() == TeamId.A;
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean pointWonByA;

            if (simulationMatchState.getServe() == TeamId.A)
                pointWonByA = r < p;
            else
                pointWonByA = r < 1 - p1;
            if (pointWonByA) {

                SquashMatchIncident squashMatchIncident = new SquashMatchIncident();
                squashMatchIncident.set(SquashMatchIncidentType.POINTWON, TeamId.A);
                matchEventResult = (SquashMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(squashMatchIncident, false);
            } else {
                SquashMatchIncident squashMatchIncident = new SquashMatchIncident();
                squashMatchIncident.set(SquashMatchIncidentType.POINTWON, TeamId.B);
                matchEventResult = (SquashMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(squashMatchIncident, false);

            }
            int currentSetNo = simulationMatchState.getGameNo(1);
            TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getSquashMatchIncidentResultType()) {
                case POINTWON:

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 3) && (simulationMatchState.getPointsB() < 3)) {
                                matchFacts.point3WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 3) && (simulationMatchState.getPointsB() == 3)) {
                                matchFacts.point3WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.point5WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.point5WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 7) && (simulationMatchState.getPointsB() < 7)) {
                                matchFacts.point7WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 7) && (simulationMatchState.getPointsB() == 7)) {
                                matchFacts.point7WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 9) && (simulationMatchState.getPointsB() < 9)) {
                                matchFacts.point9WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 9) && (simulationMatchState.getPointsB() == 9)) {
                                matchFacts.point9WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 3) && (simulationMatchState.getPointsB() < 3)) {
                                matchFacts.nextGamepoint3WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 3) && (simulationMatchState.getPointsB() == 3)) {
                                matchFacts.nextGamepoint3WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.nextGamepoint5WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 7) && (simulationMatchState.getPointsB() < 7)) {
                                matchFacts.nextGamepoint7WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 7) && (simulationMatchState.getPointsB() == 7)) {
                                matchFacts.nextGamepoint7WinnerIsA = false;
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() == 9) && (simulationMatchState.getPointsB() < 9)) {
                                matchFacts.nextGamepoint9WinnerIsA = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo + 1) {
                            if ((simulationMatchState.getPointsA() < 9) && (simulationMatchState.getPointsB() == 9)) {
                                matchFacts.nextGamepoint9WinnerIsA = false;
                            }
                        }
                    }
                    break;
                case GAMEWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo)
                            matchFacts.setWinnerCurrentIsA = true;
                    } else if (currentSetNo == startSetNo)
                        matchFacts.setWinnerCurrentIsA = false;
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                    } else
                        matchFacts.matchWinnerisA = false;
                    break;
                default:
                    break;
            }

        } while (matchEventResult.getSquashMatchIncidentResultType() != SquashMatchIncidentResultType.MATCHWON);
        ((SquashMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((SquashMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new SquashMatchMarketsFactory((SquashMatchState) matchState);

    }

}
