package ats.algo.sport.testcricket;

import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.core.baseclasses.MatchFormat;
import ats.algo.core.baseclasses.MatchParams;
import ats.algo.core.baseclasses.MatchState;
import ats.algo.core.common.TeamId;
import ats.algo.montecarloframework.MonteCarloMatch;
import ats.algo.sport.testcricket.TestCricketMatchIncident.CricketMatchIncidentType;
import ats.algo.sport.testcricket.TestCricketMatchIncidentResult.CricketMatchIncidentResultType;

public class TestCricketMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class TestCricketMatchFacts {

        int runsA;
        int runsB;
        int oversA;
        int oversB;
        int ballsFirstWicket;
        boolean currentOverA;
        boolean currentOverB;
        boolean currentWicketA;
        boolean currentWicketB;
        boolean currentBall;
        int currentRunsA;
        int currentRunsB;
        int nextRunsA;
        int nextRunsB;
        int runsFirstWicket;
        int wicketMethodA;
        int wicketMethodB;
        String wicketPlayerA;
        String wicketPlayerB;
        int inningsA;
        int inningsB;
        boolean isDraw;

        void reset() {
            runsA = 0;
            runsB = 0;
            ballsFirstWicket = 0;
            runsFirstWicket = 0;
            oversA = 1;
            oversB = 1;
            currentRunsA = 0;
            currentRunsB = 0;
            currentOverA = false;
            currentWicketA = false;
            currentOverB = false;
            currentWicketB = false;
            currentBall = true;
            wicketMethodA = -1;
            wicketMethodB = -1;
            wicketPlayerA = null;
            wicketPlayerB = null;
            isDraw = false;
        }
    }

    private TestCricketMatchState simulationMatchState;
    private TestCricketMatchFacts matchFacts;
    /*
     * % chances of what will happen per ball for T20 No Runs - 55% 1 Run - 18% 2 Runs - 2.5% 3 Runs - 0.5% 4 Runs - 11%
     * 5 Runs - 0.2% 6 Runs - 5% Wicket - 1.5%Extras - 6.3% % Chance of dismissal Caught - 63% Bowled - 16% LBW - 12%
     * Run Out - 5% Stumped - 3% Other - 1%
     */

    private static final double[] ballPer = {0.001, 0.00025, 0.00005, 0.0011, 0.00002, 0.0005, 0.00063};
    private static final double[] wicketPer = {0.63, 0.16, 0.12, 0.05, 0.03, 0.033};

    private static final double[] per = new double[ballPer.length + wicketPer.length];
    private double sum = 0;
    private double sum1to6 = 0;
    private int totalBalls;
    private int totalDays;
    private int nOversPerDay;

    public TestCricketMatch(TestCricketMatchFormat matchFormat, TestCricketMatchState matchState,
                    TestCricketMatchParams matchParams) {

        super((MatchFormat) matchFormat, (MatchState) matchState, (MatchParams) matchParams);
        monteCarloMarkets = new TestCricketMatchMarketsFactory(matchState);
        this.simulationMatchState = (TestCricketMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */

        this.matchFacts = new TestCricketMatchFacts();
        totalDays = matchFormat.getnDayinMatch();
        int ballsPerOver = matchFormat.getnBallsinOver();
        nOversPerDay = matchState.getOversPerDay();
        totalBalls = totalDays * nOversPerDay * ballsPerOver / 4;
        for (int i = 0; i < ballPer.length; i++) {
            if (i == ballPer.length - 1) {
                sum1to6 += ballPer[i];
            } else
                sum1to6 += (i + 1) * ballPer[i];
        }
        sum = sum1to6 * totalBalls * 2;
    }

    @Override
    public MonteCarloMatch clone() {
        return new TestCricketMatch((TestCricketMatchFormat) matchFormat, (TestCricketMatchState) matchState,
                        (TestCricketMatchParams) matchParams);
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int inningsA = simulationMatchState.getInningsA();
        int inningsB = simulationMatchState.getInningsB();
        TestCricketMatchIncident cricketMatchIncident = new TestCricketMatchIncident();
        cricketMatchIncident.set(CricketMatchIncidentType.BATFIRST);

        if (simulationMatchState.getBat() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                cricketMatchIncident.setTeamId(TeamId.A);
                simulationMatchState.updateStateForIncident(cricketMatchIncident, false);
            } else {
                cricketMatchIncident.setTeamId(TeamId.B);
                simulationMatchState.updateStateForIncident(cricketMatchIncident, false);
            }

        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        int[] currentPlayerOnField = simulationMatchState.getCricketPlayerNo(simulationMatchState.getBat());
        double cpa1 = ((TestCricketMatchParams) matchParams).getTeamAPlayer1().nextRandom();
        double cpa2 = ((TestCricketMatchParams) matchParams).getTeamAPlayer2().nextRandom();
        double cpa3 = ((TestCricketMatchParams) matchParams).getTeamAPlayer3().nextRandom();
        double cpa4 = ((TestCricketMatchParams) matchParams).getTeamAPlayer4().nextRandom();
        double cpa5 = ((TestCricketMatchParams) matchParams).getTeamAPlayer5().nextRandom();
        double cpa6 = ((TestCricketMatchParams) matchParams).getTeamAPlayer6().nextRandom();
        double cpa7 = ((TestCricketMatchParams) matchParams).getTeamAPlayer7().nextRandom();
        double cpa8 = ((TestCricketMatchParams) matchParams).getTeamAPlayer8().nextRandom();
        double cpa9 = ((TestCricketMatchParams) matchParams).getTeamAPlayer9().nextRandom();
        double cpa10 = ((TestCricketMatchParams) matchParams).getTeamAPlayer10().nextRandom();
        double cpa11 = ((TestCricketMatchParams) matchParams).getTeamAPlayer11().nextRandom();
        double[] cpa = {cpa1, cpa2, cpa3, cpa4, cpa5, cpa6, cpa7, cpa8, cpa9, cpa10, cpa11};
        double cpb1 = ((TestCricketMatchParams) matchParams).getTeamBPlayer1().nextRandom();
        double cpb2 = ((TestCricketMatchParams) matchParams).getTeamBPlayer2().nextRandom();
        double cpb3 = ((TestCricketMatchParams) matchParams).getTeamBPlayer3().nextRandom();
        double cpb4 = ((TestCricketMatchParams) matchParams).getTeamBPlayer4().nextRandom();
        double cpb5 = ((TestCricketMatchParams) matchParams).getTeamBPlayer5().nextRandom();
        double cpb6 = ((TestCricketMatchParams) matchParams).getTeamBPlayer6().nextRandom();
        double cpb7 = ((TestCricketMatchParams) matchParams).getTeamBPlayer7().nextRandom();
        double cpb8 = ((TestCricketMatchParams) matchParams).getTeamBPlayer8().nextRandom();
        double cpb9 = ((TestCricketMatchParams) matchParams).getTeamBPlayer9().nextRandom();
        double cpb10 = ((TestCricketMatchParams) matchParams).getTeamBPlayer10().nextRandom();
        double cpb11 = ((TestCricketMatchParams) matchParams).getTeamBPlayer11().nextRandom();
        double[] cpb = {cpb1, cpb2, cpb3, cpb4, cpb5, cpb6, cpb7, cpb8, cpb9, cpb10, cpb11};
        double ctA = ((TestCricketMatchParams) matchParams).getInningoneTeamARuns().nextRandom();
        double ctB = ((TestCricketMatchParams) matchParams).getInningoneTeamBRuns().nextRandom();
        double ta;
        double tb;
        double[][] perA1to6 = new double[cpa.length][per.length];
        double[][] perB1to6 = new double[cpb.length][per.length];

        TestCricketMatchIncidentResult matchEventResult;
        matchFacts.reset();
        double pa;
        double pb;
        double secondInningRate = 1;

        for (int x = 0; x < cpa.length; x++) {
            double wicket1to6 = 0.0088;
            if (x == currentPlayerOnField[0] || x == currentPlayerOnField[1]) {
                pa = cpa[x] > simulationMatchState.getRunsPerWicketA()[inningsA - 1][x] ? cpa[x] : cpa[x] / 2;
                pa = pa * 1.7;
                wicket1to6 = 0.0088 * (1 - (cpa[x] - ctA / 11) / totalBalls);
            } else
                pa = cpa[x];

            if (x == currentPlayerOnField[0] || x == currentPlayerOnField[1]) {
                pb = cpb[x] > simulationMatchState.getRunsPerWicketB()[inningsB - 1][x] ? cpb[x] : cpb[x] / 2;
                pb = pb * 1.7;
                wicket1to6 = 0.0088 * (1 - (cpb[x] - ctB / 11) / totalBalls);
            } else
                pb = cpb[x];

            ta = pa * 11 / sum;
            tb = pb * 11 / sum;
            perA1to6[x][0] = ballPer[0] * ta;
            for (int i = 1; i < perA1to6[0].length; i++)
                if (i > (ballPer.length - 1))
                    perA1to6[x][i] = wicket1to6 * wicketPer[i - ballPer.length] + perA1to6[x][i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perA1to6[x][i] += ballPer[m] * ta;
            if (perA1to6[x][perA1to6.length - 1] > 1) {
                for (int i = 1; i < perA1to6[0].length; i++)
                    perA1to6[x][i] = perA1to6[x][i] / perA1to6[x][perA1to6.length - 1];
            }
            perB1to6[x][0] = ballPer[0] * tb;
            for (int i = 1; i < perB1to6[0].length; i++)
                if (i > (ballPer.length - 1))
                    perB1to6[x][i] = wicket1to6 * wicketPer[i - ballPer.length] + perB1to6[x][i - 1];
                else
                    for (int m = 0; m <= i; m++)
                        perB1to6[x][i] += ballPer[m] * tb;
            if (perB1to6[x][perB1to6.length - 1] > 1) {
                for (int i = 1; i < perB1to6[0].length; i++)
                    perB1to6[x][i] = perB1to6[x][i] / perB1to6[x][perB1to6.length - 1];
            }
        }
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean serveA = simulationMatchState.getBat() == TeamId.A;
            int currentWicketA1 = simulationMatchState.getWicketsA();
            int currentWicketB1 = simulationMatchState.getWicketsB();
            cricketMatchIncident = new TestCricketMatchIncident();
            if (serveA) {
                cricketMatchIncident.setTeamId(TeamId.A);
            } else
                cricketMatchIncident.setTeamId(TeamId.B);

            if (serveA) {
                int currentWicketA = simulationMatchState.isPlayerABating()
                                ? simulationMatchState.getCricketPlayerNo(simulationMatchState.getBat())[0]
                                : simulationMatchState.getCricketPlayerNo(simulationMatchState.getBat())[1];
                if (simulationMatchState.getInningsA() > 1) {
                    if (r < (perA1to6[currentWicketA][0])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                    } else if (r < (perA1to6[currentWicketA][1])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                    } else if (r < (perA1to6[currentWicketA][2])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                    } else if (r < (perA1to6[currentWicketA][3])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                    } else if (r < (perA1to6[currentWicketA][4])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                    } else if (r < (perA1to6[currentWicketA][5])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                    } else if (r < (perA1to6[currentWicketA][6])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                    } else if (r < (perA1to6[currentWicketA][7] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                    } else if (r < (perA1to6[currentWicketA][8] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                    } else if (r < (perA1to6[currentWicketA][9] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                    } else if (r < (perA1to6[currentWicketA][10] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                    } else if (r < (perA1to6[currentWicketA][11] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                    } else if (r < (perA1to6[currentWicketA][12] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                    } else {
                        cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                    }
                } else {
                    if (r < (perA1to6[currentWicketA][0])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                    } else if (r < (perA1to6[currentWicketA][1])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                    } else if (r < (perA1to6[currentWicketA][2])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                    } else if (r < (perA1to6[currentWicketA][3])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                    } else if (r < (perA1to6[currentWicketA][4])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                    } else if (r < (perA1to6[currentWicketA][5])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                    } else if (r < (perA1to6[currentWicketA][6])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                    } else if (r < (perA1to6[currentWicketA][7])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                    } else if (r < (perA1to6[currentWicketA][8])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                    } else if (r < (perA1to6[currentWicketA][9])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                    } else if (r < (perA1to6[currentWicketA][10])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                    } else if (r < (perA1to6[currentWicketA][11])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                    } else if (r < (perA1to6[currentWicketA][12])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                    } else {
                        cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                    }
                }

            } else {
                int currentWicketB = simulationMatchState.isPlayerABating()
                                ? simulationMatchState.getCricketPlayerNo(simulationMatchState.getBat())[0]
                                : simulationMatchState.getCricketPlayerNo(simulationMatchState.getBat())[1];
                if (simulationMatchState.getInningsB() > 1) {
                    if (r < (perB1to6[currentWicketB][0])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                    } else if (r < (perB1to6[currentWicketB][1])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                    } else if (r < (perB1to6[currentWicketB][2])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                    } else if (r < (perB1to6[currentWicketB][3])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                    } else if (r < (perB1to6[currentWicketB][4])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                    } else if (r < (perB1to6[currentWicketB][5])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                    } else if (r < (perB1to6[currentWicketB][6])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                    } else if (r < (perB1to6[currentWicketB][7] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                    } else if (r < (perB1to6[currentWicketB][8] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                    } else if (r < (perB1to6[currentWicketB][9] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                    } else if (r < (perB1to6[currentWicketB][10] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                    } else if (r < (perB1to6[currentWicketB][11] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                    } else if (r < (perB1to6[currentWicketB][12] * secondInningRate)) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                    } else {
                        cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                    }
                } else {
                    if (r < (perB1to6[currentWicketB][0])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN1);
                    } else if (r < (perB1to6[currentWicketB][1])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN2);
                    } else if (r < (perB1to6[currentWicketB][2])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN3);
                    } else if (r < (perB1to6[currentWicketB][3])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN4);
                    } else if (r < (perB1to6[currentWicketB][4])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN5);
                    } else if (r < (perB1to6[currentWicketB][5])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.RUN6);
                    } else if (r < (perB1to6[currentWicketB][6])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.EXTRAS);
                    } else if (r < (perB1to6[currentWicketB][7])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_CAUGHT);
                    } else if (r < (perB1to6[currentWicketB][8])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_BOWLED);
                    } else if (r < (perB1to6[currentWicketB][9])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_LBW);
                    } else if (r < (perB1to6[currentWicketB][10])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_RUN_OUT);
                    } else if (r < (perB1to6[currentWicketB][11])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_STUMPED);
                    } else if (r < (perB1to6[currentWicketB][12])) {
                        cricketMatchIncident.set(CricketMatchIncidentType.WICKET_OTHER);
                    } else {
                        cricketMatchIncident.set(CricketMatchIncidentType.NORUNS);
                    }
                }

            }
            cricketMatchIncident.setCricketPlayerName(
                            simulationMatchState.isPlayerABating() ? simulationMatchState.getOnFieldPlayerName()[0]
                                            : simulationMatchState.getOnFieldPlayerName()[1]);
            matchEventResult = (TestCricketMatchIncidentResult) simulationMatchState
                            .updateStateForIncident(cricketMatchIncident, false);
            int x = -1;
            switch (matchEventResult.getcricketMatchIncidentResultType()) {

                case WICKET_BOWLED:
                    x++;
                case WICKET_CAUGHT:
                    x++;
                case WICKET_LBW:
                    x++;
                case WICKET_RUN_OUT:
                    x++;
                case WICKET_STUMPED:
                    x++;
                case WICKET_OTHER:
                    x++;
                    if (x != -1 && simulationMatchState.getWicketsA() == (currentWicketA1 + 1)
                                    && !matchFacts.currentWicketA && serveA) {
                        matchFacts.currentWicketA = true;
                        matchFacts.wicketMethodA = 5 - x;
                        matchFacts.wicketPlayerA = cricketMatchIncident.getCricketPlayerName();
                    }
                    if (x != -1 && simulationMatchState.getWicketsB() == (currentWicketB1 + 1)
                                    && !matchFacts.currentWicketB && !serveA) {
                        matchFacts.currentWicketB = true;
                        matchFacts.wicketMethodB = 5 - x;
                        matchFacts.wicketPlayerB = cricketMatchIncident.getCricketPlayerName();
                    }
                    if (simulationMatchState.getWicket() == 1 && matchFacts.currentBall) {
                        matchFacts.ballsFirstWicket = simulationMatchState.getBall();
                        matchFacts.runsFirstWicket = simulationMatchState.getRunsA() + simulationMatchState.getRunsB();
                        matchFacts.currentBall = false;
                    }
                case NORUNS:
                case RUN1:
                case RUN2:
                case RUN3:
                case RUN4:
                case RUN5:
                case RUN6:
                case MATCHWON:
                    matchFacts.runsA = simulationMatchState.getRunsA();
                    matchFacts.runsB = simulationMatchState.getRunsB();
                    break;
                case DRAW:
                    matchFacts.isDraw = true;
                    matchFacts.runsA = simulationMatchState.getRunsA();
                    matchFacts.runsB = simulationMatchState.getRunsB();
                    break;
                default:
                    break;
            }

        } while ((matchEventResult.getcricketMatchIncidentResultType() != CricketMatchIncidentResultType.MATCHWON)
                        && (matchEventResult
                                        .getcricketMatchIncidentResultType() != CricketMatchIncidentResultType.DRAW));
        ((TestCricketMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((TestCricketMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new TestCricketMatchMarketsFactory((TestCricketMatchState) matchState);

    }

}
