package ats.algo.sport.volleyball;

import ats.algo.core.common.TeamId;
import ats.algo.genericsupportfunctions.RandomNoGenerator;
import ats.algo.sport.volleyball.VolleyballMatchIncident.VolleyballMatchIncidentType;
import ats.algo.sport.volleyball.VolleyballMatchIncidentResult.VolleyballMatchIncidentResultType;
import ats.algo.montecarloframework.MonteCarloMatch;

public class VolleyballMatch extends MonteCarloMatch {

    /**
     * Container to hold any data generated by a single run of the Match which is not contained in MatchState and is
     * needed to generate the required statistics. eg. who won the current leg.
     * 
     * @author Robert
     * 
     */
    class VolleyballMatchFacts {

        boolean setWinnerCurrentIsA;
        boolean setWinnerCurrentIsB;
        boolean setWinnerNextIsA;
        boolean matchWinnerisA;
        boolean setWinnerNPlus2IsA;
        boolean setNextIsPlayed;
        boolean setNPlus2IsPlayed;
        boolean serveIsA;
        boolean point5WinnerIsA;
        TeamId point10LeadIsA;
        boolean point10WinnerIsA;
        TeamId point20LeadIsA;
        boolean point15WinnerIsA;
        TeamId point30LeadIsA;
        boolean point15Winner;
        boolean point30Lead;
        int pointsA;
        int pointsB;
        double pointWinningA;
        double pointWinningB;
        int setsA;
        int setsB;

        void reset() {
            setNextIsPlayed = false;
            setNPlus2IsPlayed = false;
            setWinnerCurrentIsA = false;
            setWinnerCurrentIsB = false;
            serveIsA = false;
            point5WinnerIsA = false;
            point10LeadIsA = TeamId.UNKNOWN;
            point10WinnerIsA = false;
            point20LeadIsA = TeamId.UNKNOWN;
            point15WinnerIsA = false;
            point30LeadIsA = TeamId.UNKNOWN;
            point15Winner = false;
            point30Lead = false;
            pointWinningA = 0;
            pointWinningB = 0;
            pointsA = 0;
            pointsB = 0;
            setsA = 0;
            setsB = 0;

        }
    }

    private VolleyballMatchState simulationMatchState;
    private VolleyballMatchFacts matchFacts;

    public VolleyballMatch(VolleyballMatchFormat matchFormat, VolleyballMatchState matchState,
                    VolleyballMatchParams matchParams) {

        super(matchFormat, matchState, matchParams);
        monteCarloMarkets = new VolleyballMatchMarketsFactory(matchState);
        this.simulationMatchState = (VolleyballMatchState) matchState.copy();
        /*
         * create the container for holding match facts just once rather than every time playMatch is executed - greatly
         * improves performance
         */
        this.matchFacts = new VolleyballMatchFacts();
    }

    @Override
    public MonteCarloMatch clone() {
        return new VolleyballMatch((VolleyballMatchFormat) matchFormat, (VolleyballMatchState) matchState,
                        (VolleyballMatchParams) matchParams);
    }

    @Override
    public void playMatch() {
        simulationMatchState.setEqualTo(matchState);
        int startSetNo = simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1;
        if (simulationMatchState.getServe() == TeamId.UNKNOWN)
            if (RandomNoGenerator.nextBool()) {
                simulationMatchState.setServeInFirstSet(TeamId.A);
                simulationMatchState.setServe(TeamId.A);
            } else {
                simulationMatchState.setServeInFirstSet(TeamId.B);
                simulationMatchState.setServe(TeamId.B);
            }
        /*
         * draw the prob of A winning leg as a random variable drawn from the gaussian distribution for the parameter
         * probAWinsLeg
         */
        double p = ((VolleyballMatchParams) matchParams).getOnServePctA().nextRandom();
        double p1 = ((VolleyballMatchParams) matchParams).getOnServePctB().nextRandom();

        VolleyballMatchIncidentResult matchEventResult;
        matchFacts.reset();
        matchFacts.pointWinningA = p;
        matchFacts.pointWinningB = p1;
        matchFacts.serveIsA = simulationMatchState.getServe() == TeamId.A;
        do {
            double r = RandomNoGenerator.nextDouble();

            boolean pointWonByA;
            if (simulationMatchState.getServe() != TeamId.UNKNOWN)
                if (simulationMatchState.getServe() == TeamId.A)
                    pointWonByA = r < p;
                else
                    pointWonByA = r < 1 - p1;
            else
                pointWonByA = RandomNoGenerator.nextBool();
            if (pointWonByA) {

                VolleyballMatchIncident volleyballMatchIncident = new VolleyballMatchIncident();
                volleyballMatchIncident.set(VolleyballMatchIncidentType.POINTWON, TeamId.A);
                matchEventResult = (VolleyballMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(volleyballMatchIncident, false);
            } else {
                VolleyballMatchIncident volleyballMatchIncident = new VolleyballMatchIncident();
                volleyballMatchIncident.set(VolleyballMatchIncidentType.POINTWON, TeamId.B);
                matchEventResult = (VolleyballMatchIncidentResult) simulationMatchState
                                .updateStateForIncident(volleyballMatchIncident, false);

            }
            int currentSetNo = simulationMatchState.getSetsA() + simulationMatchState.getSetsB() + 1;
            int pointNo = simulationMatchState.getPointsA() + simulationMatchState.getPointsB();
            TeamId teamId = matchEventResult.getTeamId();
            switch (matchEventResult.getVolleyballMatchIncidentResultType()) {
                case POINTWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 5) && (simulationMatchState.getPointsB() < 5)) {
                                matchFacts.point5WinnerIsA = true;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 5) && (simulationMatchState.getPointsB() == 5)) {
                                matchFacts.point5WinnerIsA = false;
                            }
                            if (pointNo == 10) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point10LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point10LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point10LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 10) && (simulationMatchState.getPointsB() < 10)) {
                                matchFacts.point10WinnerIsA = true;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 10) && (simulationMatchState.getPointsB() == 10)) {
                                matchFacts.point10WinnerIsA = false;
                            }
                            if (pointNo == 20) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point20LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point20LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point20LeadIsA = TeamId.UNKNOWN;
                                }
                            }
                        }
                    }

                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() == 15) && (simulationMatchState.getPointsB() < 15)) {
                                matchFacts.point15WinnerIsA = true;
                                matchFacts.point15Winner = true;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point30LeadIsA = TeamId.UNKNOWN;
                                }
                                matchFacts.point30Lead = true;
                            }
                        }
                    } else {
                        if (currentSetNo == startSetNo) {
                            if ((simulationMatchState.getPointsA() < 15) && (simulationMatchState.getPointsB() == 15)) {
                                matchFacts.point15WinnerIsA = false;
                                matchFacts.point15Winner = true;
                            }
                            if (pointNo == 30) {
                                if (simulationMatchState.getPointsA() > simulationMatchState.getPointsB()) {
                                    matchFacts.point30LeadIsA = TeamId.A;
                                } else if (simulationMatchState.getPointsB() > simulationMatchState.getPointsA()) {
                                    matchFacts.point30LeadIsA = TeamId.B;
                                } else {
                                    matchFacts.point30LeadIsA = TeamId.UNKNOWN;
                                }
                                matchFacts.point30Lead = true;
                            }
                        }
                    }
                    break;

                case SETWON:
                    if (TeamId.A == teamId) {
                        if (currentSetNo == startSetNo)
                            matchFacts.setWinnerCurrentIsA = true;
                    } else if (currentSetNo == startSetNo)
                        matchFacts.setWinnerCurrentIsA = false;
                    break;
                case MATCHWON:
                    if (TeamId.A == teamId) {
                        matchFacts.matchWinnerisA = true;
                    } else
                        matchFacts.matchWinnerisA = false;
                    break;
                default:
                    break;
            }

        } while (matchEventResult.getVolleyballMatchIncidentResultType() != VolleyballMatchIncidentResultType.MATCHWON);
        ((VolleyballMatchMarketsFactory) monteCarloMarkets).updateStats(simulationMatchState, matchFacts);
    }

    @Override
    public void consolidateStats(MonteCarloMatch match) {
        this.monteCarloMarkets.consolidate(((VolleyballMatch) match).monteCarloMarkets);
    }

    @Override
    public void resetStatistics() {
        monteCarloMarkets = new VolleyballMatchMarketsFactory((VolleyballMatchState) matchState);
    }

}
